'use strict';

// Text sent by the Telegram bot. Values are plain text; callers escape dynamic
// values before interpolation when they embed the result in Telegram HTML.
const COPY = {
    en: {
        play: '🎮 Play', openSpark: 'Open Spark',
        tttName: 'Tic-Tac-Toe', checkersName: 'Checkers',
        blockBlastName: 'Block Blast', minesweeperName: 'Minesweeper', towerName: 'Tower',
        sudokuName: 'Sudoku', wordleName: 'Wordle', referralsName: 'Referrers',
        inviteTtt: '{name} wants to play Tic-Tac-Toe!\n\nTap any square to accept the challenge.',
        inviteCheckers: '{name} wants to play Checkers!\n\nTap one of your pieces to accept the challenge.',
        tttDescription: 'Play with someone in this chat!',
        checkersDescription: 'Play Checkers with someone in this chat!',
        topTitle: 'Top {game}', topDescription: 'Show the {game} leaderboard',
        topSendDescription: 'Tap to send the leaderboard to this chat',
        topUnavailable: 'Leaderboard temporarily unavailable', noResults: 'No results yet',
        topPlayers: '{game} — Top players', rankYou: 'You: #{rank} — {score}',
        rankTop: 'You’re in the top {rank}!', player: 'Player',
        gameExpired: 'Game not found or expired', moveBusy: 'Move already in progress',
        awaitOpponent: 'Wait for an opponent!', gameStartedTurn: 'Game started! {name} goes first',
        notParticipant: 'You’re not playing in this game!', notYourTurn: 'It’s not your turn!',
        cellOccupied: 'That square is occupied!', draw: 'Draw!', victory: '{name} wins!', victoryToast: 'Victory!',
        firstTurn: 'First turn: {name} ({symbol})', turn: 'Turn: {name} ({symbol})',
        gameFinished: 'This game is already over!', selectCell: '{name}: choose a square',
        mustCapture: 'You must capture!', captureAgain: '{name}: capture again',
        invalidMove: 'You can’t move there!', checkerCannotMove: 'This piece can’t move!',
        chooseCaptureChecker: 'Choose a piece that can capture!',
        chooseMove: 'Choose where to move', chooseOwnChecker: 'Choose one of your pieces!',
        availableTops: 'Available leaderboards:', topLoadError: 'Could not load the leaderboard',
        gameNotFound: 'Game not found. Send /top to see the list.',
        displacedLeader: 'Someone passed you on the {game} leaderboard! You were #1 and are now #2. Try to reclaim the lead!',
        displacedRank: 'Someone moved you from #{oldRank} to #{newRank} on the {game} leaderboard!',
        viewTop: '🏆 View leaderboard',
    },
    ru: {
        play: '🎮 Играть', openSpark: 'Открыть Spark',
        tttName: 'Крестики-нолики', checkersName: 'Шашки',
        blockBlastName: 'Блок Бласт', minesweeperName: 'Сапёр', towerName: 'Башня',
        sudokuName: 'Судоку', wordleName: 'Вордли', referralsName: 'Рефералы',
        inviteTtt: '{name} хочет сыграть в крестики-нолики!\n\nНажмите любую клетку, чтобы принять вызов.',
        inviteCheckers: '{name} хочет сыграть в шашки!\n\nНажмите на любую свою шашку, чтобы принять вызов.',
        tttDescription: 'Сыграйте с кем-то из чата!',
        checkersDescription: 'Сыграйте в шашки с кем-то из чата!',
        topTitle: 'Топ {game}', topDescription: 'Показать топ игроков в {game}',
        topSendDescription: 'Нажмите, чтобы отправить топ в чат',
        topUnavailable: 'Топ временно недоступен', noResults: 'Пока нет результатов',
        topPlayers: '{game} — Топ игроков', rankYou: 'Вы: #{rank} — {score}',
        rankTop: 'Вы в топ-{rank}!', player: 'Игрок',
        gameExpired: 'Игра не найдена или истекла', moveBusy: 'Ход уже обрабатывается',
        awaitOpponent: 'Ожидайте соперника!', gameStartedTurn: 'Игра началась! Первый ход: {name}',
        notParticipant: 'Вы не участвуете в этой игре!', notYourTurn: 'Сейчас не ваш ход!',
        cellOccupied: 'Клетка уже занята!', draw: 'Ничья!', victory: '{name} победил!', victoryToast: 'Победа!',
        firstTurn: 'Первый ход: {name} ({symbol})', turn: 'Ход: {name} ({symbol})',
        gameFinished: 'Игра уже завершена!', selectCell: '{name}: выберите клетку',
        mustCapture: 'Нужно бить!', captureAgain: '{name}: бейте ещё',
        invalidMove: 'Нельзя туда ходить!', checkerCannotMove: 'Эта шашка не может ходить!',
        chooseCaptureChecker: 'Выберите шашку, которая может бить!',
        chooseMove: 'Выберите, куда ходить', chooseOwnChecker: 'Выберите свою шашку!',
        availableTops: 'Доступные топы:', topLoadError: 'Ошибка загрузки топа',
        gameNotFound: 'Игра не найдена. Напишите /top для списка.',
        displacedLeader: 'Кто-то обошёл вас в топе {game}! Вы были на 1-м месте, теперь на 2-м. Попробуйте вернуть лидерство!',
        displacedRank: 'Кто-то сместил вас с {oldRank}-го на {newRank}-е место в топе {game}!',
        viewTop: '🏆 Посмотреть топ',
    },
    zh: {
        play: '🎮 开始游戏', openSpark: '打开 Spark',
        tttName: '井字棋', checkersName: '跳棋',
        blockBlastName: '方块爆破', minesweeperName: '扫雷', towerName: '叠塔',
        sudokuName: '数独', wordleName: '猜词', referralsName: '邀请达人',
        inviteTtt: '{name} 想玩井字棋！\n\n点击任意格子接受挑战。',
        inviteCheckers: '{name} 想玩跳棋！\n\n点击自己的棋子接受挑战。',
        tttDescription: '与聊天中的好友对战！',
        checkersDescription: '与聊天中的好友玩跳棋！',
        topTitle: '{game} 排行榜', topDescription: '查看{game}排行榜',
        topSendDescription: '点击将排行榜发送到聊天中',
        topUnavailable: '排行榜暂时无法查看', noResults: '暂无成绩',
        topPlayers: '{game} — 玩家排行榜', rankYou: '你：第 {rank} 名 — {score}',
        rankTop: '你进入了前 {rank} 名！', player: '玩家',
        gameExpired: '游戏不存在或已过期', moveBusy: '正在处理上一步',
        awaitOpponent: '请等待对手！', gameStartedTurn: '游戏开始！{name} 先手',
        notParticipant: '你没有参加这局游戏！', notYourTurn: '还没轮到你！',
        cellOccupied: '这个格子已被占用！', draw: '平局！', victory: '{name} 获胜！', victoryToast: '胜利！',
        firstTurn: '先手：{name}（{symbol}）', turn: '轮到：{name}（{symbol}）',
        gameFinished: '游戏已结束！', selectCell: '{name}：请选择格子',
        mustCapture: '必须吃子！', captureAgain: '{name}：继续吃子',
        invalidMove: '不能走到那里！', checkerCannotMove: '这枚棋子无法移动！',
        chooseCaptureChecker: '请选择可以吃子的棋子！',
        chooseMove: '请选择落子位置', chooseOwnChecker: '请选择自己的棋子！',
        availableTops: '可查看的排行榜：', topLoadError: '排行榜加载失败',
        gameNotFound: '未找到游戏。发送 /top 查看列表。',
        displacedLeader: '有人在{game}排行榜上超过了你！你从第 1 名降到了第 2 名。快去夺回榜首！',
        displacedRank: '有人在{game}排行榜上将你从第 {oldRank} 名挤到了第 {newRank} 名！',
        viewTop: '🏆 查看排行榜',
    },
    es: {
        play: '🎮 Jugar', openSpark: 'Abrir Spark',
        tttName: 'Tres en raya', checkersName: 'Damas',
        blockBlastName: 'Block Blast', minesweeperName: 'Buscaminas', towerName: 'Torre',
        sudokuName: 'Sudoku', wordleName: 'Wordle', referralsName: 'Referidos',
        inviteTtt: '¡{name} quiere jugar al tres en raya!\n\nToca cualquier casilla para aceptar el desafío.',
        inviteCheckers: '¡{name} quiere jugar a las damas!\n\nToca una de tus fichas para aceptar el desafío.',
        tttDescription: '¡Juega con alguien de este chat!',
        checkersDescription: '¡Juega a las damas con alguien de este chat!',
        topTitle: 'Clasificación de {game}', topDescription: 'Ver la clasificación de {game}',
        topSendDescription: 'Toca para enviar la clasificación al chat',
        topUnavailable: 'La clasificación no está disponible por ahora', noResults: 'Aún no hay resultados',
        topPlayers: '{game} — Mejores jugadores', rankYou: 'Tú: #{rank} — {score}',
        rankTop: '¡Estás entre los {rank} mejores!', player: 'Jugador',
        gameExpired: 'Partida no encontrada o caducada', moveBusy: 'El movimiento aún se está procesando',
        awaitOpponent: '¡Espera a tu rival!', gameStartedTurn: '¡Comenzó la partida! Empieza {name}',
        notParticipant: '¡No participas en esta partida!', notYourTurn: '¡No es tu turno!',
        cellOccupied: '¡La casilla está ocupada!', draw: '¡Empate!', victory: '¡Gana {name}!', victoryToast: '¡Victoria!',
        firstTurn: 'Primer turno: {name} ({symbol})', turn: 'Turno: {name} ({symbol})',
        gameFinished: '¡Esta partida ya terminó!', selectCell: '{name}: elige una casilla',
        mustCapture: '¡Debes capturar!', captureAgain: '{name}: captura otra vez',
        invalidMove: '¡No puedes mover ahí!', checkerCannotMove: '¡Esta ficha no puede moverse!',
        chooseCaptureChecker: '¡Elige una ficha que pueda capturar!',
        chooseMove: 'Elige dónde mover', chooseOwnChecker: '¡Elige una de tus fichas!',
        availableTops: 'Clasificaciones disponibles:', topLoadError: 'No se pudo cargar la clasificación',
        gameNotFound: 'Juego no encontrado. Envía /top para ver la lista.',
        displacedLeader: '¡Alguien te superó en la clasificación de {game}! Pasaste del puesto 1 al 2. ¡Recupera el liderato!',
        displacedRank: '¡Alguien te desplazó del puesto {oldRank} al {newRank} en la clasificación de {game}!',
        viewTop: '🏆 Ver clasificación',
    },
    pt: {
        play: '🎮 Jogar', openSpark: 'Abrir Spark',
        tttName: 'Jogo da velha', checkersName: 'Damas',
        blockBlastName: 'Block Blast', minesweeperName: 'Campo Minado', towerName: 'Torre',
        sudokuName: 'Sudoku', wordleName: 'Wordle', referralsName: 'Indicações',
        inviteTtt: '{name} quer jogar jogo da velha!\n\nToque em qualquer casa para aceitar o desafio.',
        inviteCheckers: '{name} quer jogar damas!\n\nToque em uma das suas peças para aceitar o desafio.',
        tttDescription: 'Jogue com alguém deste chat!',
        checkersDescription: 'Jogue damas com alguém deste chat!',
        topTitle: 'Ranking de {game}', topDescription: 'Ver o ranking de {game}',
        topSendDescription: 'Toque para enviar o ranking ao chat',
        topUnavailable: 'Ranking temporariamente indisponível', noResults: 'Ainda não há resultados',
        topPlayers: '{game} — Melhores jogadores', rankYou: 'Você: #{rank} — {score}',
        rankTop: 'Você está entre os {rank} melhores!', player: 'Jogador',
        gameExpired: 'Partida não encontrada ou expirada', moveBusy: 'A jogada ainda está sendo processada',
        awaitOpponent: 'Aguarde um adversário!', gameStartedTurn: 'A partida começou! {name} joga primeiro',
        notParticipant: 'Você não participa desta partida!', notYourTurn: 'Não é a sua vez!',
        cellOccupied: 'Essa casa está ocupada!', draw: 'Empate!', victory: '{name} venceu!', victoryToast: 'Vitória!',
        firstTurn: 'Primeira jogada: {name} ({symbol})', turn: 'Vez de {name} ({symbol})',
        gameFinished: 'Esta partida já terminou!', selectCell: '{name}: escolha uma casa',
        mustCapture: 'Você precisa capturar!', captureAgain: '{name}: capture novamente',
        invalidMove: 'Você não pode mover para lá!', checkerCannotMove: 'Esta peça não pode se mover!',
        chooseCaptureChecker: 'Escolha uma peça que possa capturar!',
        chooseMove: 'Escolha para onde mover', chooseOwnChecker: 'Escolha uma de suas peças!',
        availableTops: 'Rankings disponíveis:', topLoadError: 'Não foi possível carregar o ranking',
        gameNotFound: 'Jogo não encontrado. Envie /top para ver a lista.',
        displacedLeader: 'Alguém ultrapassou você no ranking de {game}! Você caiu do 1º para o 2º lugar. Tente recuperar a liderança!',
        displacedRank: 'Alguém fez você cair do {oldRank}º para o {newRank}º lugar no ranking de {game}!',
        viewTop: '🏆 Ver ranking',
    },
    id: {
        play: '🎮 Main', openSpark: 'Buka Spark',
        tttName: 'Tic-Tac-Toe', checkersName: 'Dam',
        blockBlastName: 'Block Blast', minesweeperName: 'Sapu Ranjau', towerName: 'Menara',
        sudokuName: 'Sudoku', wordleName: 'Wordle', referralsName: 'Pengundang',
        inviteTtt: '{name} ingin bermain Tic-Tac-Toe!\n\nKetuk kotak mana saja untuk menerima tantangan.',
        inviteCheckers: '{name} ingin bermain dam!\n\nKetuk salah satu bidakmu untuk menerima tantangan.',
        tttDescription: 'Bermain dengan teman di obrolan ini!',
        checkersDescription: 'Bermain dam dengan teman di obrolan ini!',
        topTitle: 'Peringkat {game}', topDescription: 'Lihat peringkat {game}',
        topSendDescription: 'Ketuk untuk mengirim peringkat ke obrolan',
        topUnavailable: 'Peringkat sementara tidak tersedia', noResults: 'Belum ada hasil',
        topPlayers: '{game} — Pemain teratas', rankYou: 'Kamu: #{rank} — {score}',
        rankTop: 'Kamu masuk {rank} besar!', player: 'Pemain',
        gameExpired: 'Permainan tidak ditemukan atau sudah kedaluwarsa', moveBusy: 'Langkah sebelumnya masih diproses',
        awaitOpponent: 'Tunggu lawan!', gameStartedTurn: 'Permainan dimulai! {name} jalan lebih dulu',
        notParticipant: 'Kamu tidak ikut permainan ini!', notYourTurn: 'Belum giliranmu!',
        cellOccupied: 'Kotak itu sudah terisi!', draw: 'Seri!', victory: '{name} menang!', victoryToast: 'Menang!',
        firstTurn: 'Giliran pertama: {name} ({symbol})', turn: 'Giliran {name} ({symbol})',
        gameFinished: 'Permainan ini sudah selesai!', selectCell: '{name}: pilih kotak',
        mustCapture: 'Kamu harus memakan bidak!', captureAgain: '{name}: makan bidak lagi',
        invalidMove: 'Tidak bisa bergerak ke sana!', checkerCannotMove: 'Bidak ini tidak bisa bergerak!',
        chooseCaptureChecker: 'Pilih bidak yang bisa memakan!',
        chooseMove: 'Pilih tujuan langkah', chooseOwnChecker: 'Pilih salah satu bidakmu!',
        availableTops: 'Peringkat yang tersedia:', topLoadError: 'Gagal memuat peringkat',
        gameNotFound: 'Permainan tidak ditemukan. Kirim /top untuk melihat daftar.',
        displacedLeader: 'Seseorang menyalipmu di peringkat {game}! Kamu turun dari posisi 1 ke posisi 2. Rebut kembali posisi teratas!',
        displacedRank: 'Seseorang menggesermu dari posisi {oldRank} ke {newRank} di peringkat {game}!',
        viewTop: '🏆 Lihat peringkat',
    },
    fr: {
        play: '🎮 Jouer', openSpark: 'Ouvrir Spark',
        tttName: 'Morpion', checkersName: 'Dames',
        blockBlastName: 'Block Blast', minesweeperName: 'Démineur', towerName: 'Tour',
        sudokuName: 'Sudoku', wordleName: 'Wordle', referralsName: 'Parrainages',
        inviteTtt: '{name} veut jouer au morpion !\n\nTouchez une case pour relever le défi.',
        inviteCheckers: '{name} veut jouer aux dames !\n\nTouchez l’un de vos pions pour relever le défi.',
        tttDescription: 'Jouez avec quelqu’un de ce chat !',
        checkersDescription: 'Jouez aux dames avec quelqu’un de ce chat !',
        topTitle: 'Classement {game}', topDescription: 'Afficher le classement {game}',
        topSendDescription: 'Touchez pour envoyer le classement dans le chat',
        topUnavailable: 'Classement temporairement indisponible', noResults: 'Aucun résultat pour le moment',
        topPlayers: '{game} — Meilleurs joueurs', rankYou: 'Vous : n° {rank} — {score}',
        rankTop: 'Vous êtes dans le top {rank} !', player: 'Joueur',
        gameExpired: 'Partie introuvable ou expirée', moveBusy: 'Le coup précédent est encore en cours',
        awaitOpponent: 'Attendez un adversaire !', gameStartedTurn: 'La partie commence ! {name} joue en premier',
        notParticipant: 'Vous ne participez pas à cette partie !', notYourTurn: 'Ce n’est pas votre tour !',
        cellOccupied: 'Cette case est occupée !', draw: 'Match nul !', victory: '{name} a gagné !', victoryToast: 'Victoire !',
        firstTurn: 'Premier tour : {name} ({symbol})', turn: 'Tour de {name} ({symbol})',
        gameFinished: 'Cette partie est déjà terminée !', selectCell: '{name} : choisissez une case',
        mustCapture: 'Vous devez prendre un pion !', captureAgain: '{name} : prenez encore un pion',
        invalidMove: 'Déplacement impossible !', checkerCannotMove: 'Ce pion ne peut pas bouger !',
        chooseCaptureChecker: 'Choisissez un pion qui peut prendre !',
        chooseMove: 'Choisissez où jouer', chooseOwnChecker: 'Choisissez l’un de vos pions !',
        availableTops: 'Classements disponibles :', topLoadError: 'Impossible de charger le classement',
        gameNotFound: 'Jeu introuvable. Envoyez /top pour voir la liste.',
        displacedLeader: 'Quelqu’un vous a dépassé au classement {game} ! Vous êtes passé de la 1re à la 2e place. Reprenez la tête !',
        displacedRank: 'Quelqu’un vous a fait passer de la place {oldRank} à la place {newRank} au classement {game} !',
        viewTop: '🏆 Voir le classement',
    },
    ja: {
        play: '🎮 プレイ', openSpark: 'Spark を開く',
        tttName: '三目並べ', checkersName: 'チェッカー',
        blockBlastName: 'ブロックブラスト', minesweeperName: 'マインスイーパー', towerName: 'タワー',
        sudokuName: '数独', wordleName: 'ワードル', referralsName: '紹介ランキング',
        inviteTtt: '{name} が三目並べに挑戦しています！\n\nマスをタップして対戦を始めましょう。',
        inviteCheckers: '{name} がチェッカーに挑戦しています！\n\n自分の駒をタップして対戦を始めましょう。',
        tttDescription: 'このチャットの相手と対戦！',
        checkersDescription: 'このチャットの相手とチェッカーで対戦！',
        topTitle: '{game} ランキング', topDescription: '{game} のランキングを見る',
        topSendDescription: 'タップしてランキングをチャットに送信',
        topUnavailable: 'ランキングは一時的に利用できません', noResults: 'まだ記録がありません',
        topPlayers: '{game} — 上位プレイヤー', rankYou: 'あなた：{rank} 位 — {score}',
        rankTop: 'トップ {rank} 入りです！', player: 'プレイヤー',
        gameExpired: '対戦が見つからないか、有効期限が切れました', moveBusy: '前の手を処理中です',
        awaitOpponent: '対戦相手を待ってください！', gameStartedTurn: '対戦開始！{name} が先手です',
        notParticipant: 'この対戦には参加していません！', notYourTurn: 'まだあなたの番ではありません！',
        cellOccupied: 'そのマスは埋まっています！', draw: '引き分け！', victory: '{name} の勝ち！', victoryToast: '勝利！',
        firstTurn: '先手：{name}（{symbol}）', turn: '次の手番：{name}（{symbol}）',
        gameFinished: 'この対戦は終了しました！', selectCell: '{name}：マスを選んでください',
        mustCapture: '駒を取る必要があります！', captureAgain: '{name}：続けて駒を取ってください',
        invalidMove: 'そこには動かせません！', checkerCannotMove: 'この駒は動かせません！',
        chooseCaptureChecker: '相手の駒を取れる駒を選んでください！',
        chooseMove: '移動先を選んでください', chooseOwnChecker: '自分の駒を選んでください！',
        availableTops: '利用できるランキング：', topLoadError: 'ランキングを読み込めませんでした',
        gameNotFound: 'ゲームが見つかりません。/top で一覧を確認してください。',
        displacedLeader: '{game} のランキングで追い抜かれました！1 位から 2 位に下がりました。首位を取り戻しましょう！',
        displacedRank: '{game} のランキングで {oldRank} 位から {newRank} 位に下がりました！',
        viewTop: '🏆 ランキングを見る',
    },
    de: {
        play: '🎮 Spielen', openSpark: 'Spark öffnen',
        tttName: 'Tic-Tac-Toe', checkersName: 'Dame',
        blockBlastName: 'Block Blast', minesweeperName: 'Minesweeper', towerName: 'Turm',
        sudokuName: 'Sudoku', wordleName: 'Wordle', referralsName: 'Einladungen',
        inviteTtt: '{name} möchte Tic-Tac-Toe spielen!\n\nTippe auf ein Feld, um die Herausforderung anzunehmen.',
        inviteCheckers: '{name} möchte Dame spielen!\n\nTippe auf einen deiner Steine, um die Herausforderung anzunehmen.',
        tttDescription: 'Spiele mit jemandem aus diesem Chat!',
        checkersDescription: 'Spiele Dame mit jemandem aus diesem Chat!',
        topTitle: '{game}-Rangliste', topDescription: '{game}-Rangliste anzeigen',
        topSendDescription: 'Tippe, um die Rangliste im Chat zu teilen',
        topUnavailable: 'Rangliste vorübergehend nicht verfügbar', noResults: 'Noch keine Ergebnisse',
        topPlayers: '{game} — Beste Spieler', rankYou: 'Du: Platz {rank} — {score}',
        rankTop: 'Du bist unter den besten {rank}!', player: 'Spieler',
        gameExpired: 'Spiel nicht gefunden oder abgelaufen', moveBusy: 'Der vorherige Zug wird noch verarbeitet',
        awaitOpponent: 'Warte auf einen Gegner!', gameStartedTurn: 'Das Spiel beginnt! {name} ist zuerst dran',
        notParticipant: 'Du spielst bei dieser Partie nicht mit!', notYourTurn: 'Du bist noch nicht am Zug!',
        cellOccupied: 'Dieses Feld ist besetzt!', draw: 'Unentschieden!', victory: '{name} hat gewonnen!', victoryToast: 'Sieg!',
        firstTurn: 'Erster Zug: {name} ({symbol})', turn: 'Am Zug: {name} ({symbol})',
        gameFinished: 'Dieses Spiel ist bereits vorbei!', selectCell: '{name}: Wähle ein Feld',
        mustCapture: 'Du musst schlagen!', captureAgain: '{name}: Schlage noch einmal',
        invalidMove: 'Dorthin kannst du nicht ziehen!', checkerCannotMove: 'Dieser Stein kann nicht ziehen!',
        chooseCaptureChecker: 'Wähle einen Stein, der schlagen kann!',
        chooseMove: 'Wähle ein Zielfeld', chooseOwnChecker: 'Wähle einen deiner Steine!',
        availableTops: 'Verfügbare Ranglisten:', topLoadError: 'Rangliste konnte nicht geladen werden',
        gameNotFound: 'Spiel nicht gefunden. Sende /top für die Liste.',
        displacedLeader: 'Jemand hat dich in der {game}-Rangliste überholt! Du bist von Platz 1 auf Platz 2 gefallen. Hol dir die Führung zurück!',
        displacedRank: 'Jemand hat dich in der {game}-Rangliste von Platz {oldRank} auf Platz {newRank} verdrängt!',
        viewTop: '🏆 Rangliste ansehen',
    },
    ko: {
        play: '🎮 플레이', openSpark: 'Spark 열기',
        tttName: '틱택토', checkersName: '체커',
        blockBlastName: '블록 블라스트', minesweeperName: '지뢰찾기', towerName: '타워',
        sudokuName: '스도쿠', wordleName: '워들', referralsName: '친구 초대',
        inviteTtt: '{name}님이 틱택토 대결을 신청했어요!\n\n아무 칸이나 눌러 도전을 받아 주세요.',
        inviteCheckers: '{name}님이 체커 대결을 신청했어요!\n\n내 말을 눌러 도전을 받아 주세요.',
        tttDescription: '채팅방 친구와 대결하세요!',
        checkersDescription: '채팅방 친구와 체커를 플레이하세요!',
        topTitle: '{game} 순위', topDescription: '{game} 순위 보기',
        topSendDescription: '눌러서 순위를 채팅방에 보내기',
        topUnavailable: '현재 순위를 볼 수 없습니다', noResults: '아직 기록이 없습니다',
        topPlayers: '{game} — 상위 플레이어', rankYou: '나: {rank}위 — {score}',
        rankTop: '상위 {rank}위 안에 들었어요!', player: '플레이어',
        gameExpired: '게임을 찾을 수 없거나 만료되었습니다', moveBusy: '이전 수를 처리하고 있습니다',
        awaitOpponent: '상대방을 기다려 주세요!', gameStartedTurn: '게임 시작! {name}님이 먼저 둡니다',
        notParticipant: '이 게임의 참가자가 아닙니다!', notYourTurn: '아직 차례가 아닙니다!',
        cellOccupied: '이미 선택된 칸입니다!', draw: '무승부!', victory: '{name}님 승리!', victoryToast: '승리!',
        firstTurn: '첫 차례: {name} ({symbol})', turn: '차례: {name} ({symbol})',
        gameFinished: '이미 끝난 게임입니다!', selectCell: '{name}: 칸을 선택하세요',
        mustCapture: '반드시 상대 말을 잡아야 합니다!', captureAgain: '{name}: 한 번 더 잡으세요',
        invalidMove: '그곳으로 이동할 수 없습니다!', checkerCannotMove: '이 말은 움직일 수 없습니다!',
        chooseCaptureChecker: '상대 말을 잡을 수 있는 말을 선택하세요!',
        chooseMove: '이동할 칸을 선택하세요', chooseOwnChecker: '내 말을 선택하세요!',
        availableTops: '볼 수 있는 순위:', topLoadError: '순위를 불러오지 못했습니다',
        gameNotFound: '게임을 찾을 수 없습니다. /top을 보내 목록을 확인하세요.',
        displacedLeader: '{game} 순위에서 다른 플레이어가 앞질렀어요! 1위에서 2위로 내려갔습니다. 다시 1위에 도전하세요!',
        displacedRank: '{game} 순위에서 {oldRank}위에서 {newRank}위로 밀려났어요!',
        viewTop: '🏆 순위 보기',
    },
    tr: {
        play: '🎮 Oyna', openSpark: 'Spark’ı aç',
        tttName: 'XOX', checkersName: 'Dama',
        blockBlastName: 'Block Blast', minesweeperName: 'Mayın Tarlası', towerName: 'Kule',
        sudokuName: 'Sudoku', wordleName: 'Wordle', referralsName: 'Davet Edenler',
        inviteTtt: '{name} XOX oynamak istiyor!\n\nMeydan okumayı kabul etmek için bir kareye dokun.',
        inviteCheckers: '{name} dama oynamak istiyor!\n\nMeydan okumayı kabul etmek için kendi taşlarından birine dokun.',
        tttDescription: 'Bu sohbetteki biriyle oyna!',
        checkersDescription: 'Bu sohbetteki biriyle dama oyna!',
        topTitle: '{game} sıralaması', topDescription: '{game} sıralamasını göster',
        topSendDescription: 'Sıralamayı sohbete göndermek için dokun',
        topUnavailable: 'Sıralama geçici olarak kullanılamıyor', noResults: 'Henüz sonuç yok',
        topPlayers: '{game} — En iyi oyuncular', rankYou: 'Sen: #{rank} — {score}',
        rankTop: 'İlk {rank} arasındasın!', player: 'Oyuncu',
        gameExpired: 'Oyun bulunamadı veya süresi doldu', moveBusy: 'Önceki hamle işleniyor',
        awaitOpponent: 'Rakibini bekle!', gameStartedTurn: 'Oyun başladı! İlk hamle {name} oyuncusunun',
        notParticipant: 'Bu oyunda değilsin!', notYourTurn: 'Sıra sende değil!',
        cellOccupied: 'Bu kare dolu!', draw: 'Berabere!', victory: '{name} kazandı!', victoryToast: 'Zafer!',
        firstTurn: 'İlk hamle: {name} ({symbol})', turn: 'Sıra: {name} ({symbol})',
        gameFinished: 'Bu oyun zaten bitti!', selectCell: '{name}: bir kare seç',
        mustCapture: 'Taş almak zorundasın!', captureAgain: '{name}: bir taş daha al',
        invalidMove: 'Oraya gidemezsin!', checkerCannotMove: 'Bu taş hareket edemez!',
        chooseCaptureChecker: 'Taş alabilen bir taş seç!',
        chooseMove: 'Gideceğin yeri seç', chooseOwnChecker: 'Kendi taşlarından birini seç!',
        availableTops: 'Mevcut sıralamalar:', topLoadError: 'Sıralama yüklenemedi',
        gameNotFound: 'Oyun bulunamadı. Liste için /top gönder.',
        displacedLeader: 'Biri {game} sıralamasında seni geçti! 1. sıradan 2. sıraya düştün. Liderliği geri al!',
        displacedRank: 'Biri seni {game} sıralamasında {oldRank}. sıradan {newRank}. sıraya düşürdü!',
        viewTop: '🏆 Sıralamayı gör',
    },
    vi: {
        play: '🎮 Chơi', openSpark: 'Mở Spark',
        tttName: 'Cờ ca-rô', checkersName: 'Cờ đam',
        blockBlastName: 'Block Blast', minesweeperName: 'Dò mìn', towerName: 'Tháp',
        sudokuName: 'Sudoku', wordleName: 'Wordle', referralsName: 'Mời bạn bè',
        inviteTtt: '{name} muốn chơi cờ ca-rô!\n\nChạm vào một ô bất kỳ để nhận lời thách đấu.',
        inviteCheckers: '{name} muốn chơi cờ đam!\n\nChạm vào một quân cờ của bạn để nhận lời thách đấu.',
        tttDescription: 'Chơi cùng một người trong cuộc trò chuyện này!',
        checkersDescription: 'Chơi cờ đam cùng một người trong cuộc trò chuyện này!',
        topTitle: 'Bảng xếp hạng {game}', topDescription: 'Xem bảng xếp hạng {game}',
        topSendDescription: 'Chạm để gửi bảng xếp hạng vào cuộc trò chuyện',
        topUnavailable: 'Bảng xếp hạng tạm thời không khả dụng', noResults: 'Chưa có kết quả',
        topPlayers: '{game} — Người chơi dẫn đầu', rankYou: 'Bạn: hạng {rank} — {score}',
        rankTop: 'Bạn đã vào top {rank}!', player: 'Người chơi',
        gameExpired: 'Không tìm thấy ván chơi hoặc ván đã hết hạn', moveBusy: 'Nước đi trước vẫn đang được xử lý',
        awaitOpponent: 'Hãy chờ đối thủ!', gameStartedTurn: 'Ván chơi bắt đầu! {name} đi trước',
        notParticipant: 'Bạn không tham gia ván này!', notYourTurn: 'Chưa đến lượt bạn!',
        cellOccupied: 'Ô này đã có quân!', draw: 'Hòa!', victory: '{name} thắng!', victoryToast: 'Chiến thắng!',
        firstTurn: 'Lượt đầu: {name} ({symbol})', turn: 'Lượt của {name} ({symbol})',
        gameFinished: 'Ván chơi đã kết thúc!', selectCell: '{name}: chọn một ô',
        mustCapture: 'Bạn phải ăn quân!', captureAgain: '{name}: ăn thêm quân nữa',
        invalidMove: 'Không thể đi tới đó!', checkerCannotMove: 'Quân này không thể di chuyển!',
        chooseCaptureChecker: 'Chọn quân có thể ăn!',
        chooseMove: 'Chọn ô muốn đi tới', chooseOwnChecker: 'Chọn một quân của bạn!',
        availableTops: 'Các bảng xếp hạng:', topLoadError: 'Không thể tải bảng xếp hạng',
        gameNotFound: 'Không tìm thấy trò chơi. Gửi /top để xem danh sách.',
        displacedLeader: 'Ai đó đã vượt bạn trên bảng xếp hạng {game}! Bạn từ hạng 1 xuống hạng 2. Hãy giành lại ngôi đầu!',
        displacedRank: 'Ai đó đã đẩy bạn từ hạng {oldRank} xuống hạng {newRank} trên bảng xếp hạng {game}!',
        viewTop: '🏆 Xem bảng xếp hạng',
    },
};

const GAME_KEYS = Object.freeze({
    bb_best_score: 'blockBlastName',
    saper_wins: 'minesweeperName',
    saper_best_6: 'minesweeperName',
    saper_best_8: 'minesweeperName',
    saper_best_10: 'minesweeperName',
    saper_best_15: 'minesweeperName',
    tower_best: 'towerName',
    tower_combo: 'towerName',
    sudoku_wins: 'sudokuName',
    checkers_wins_pve: 'checkersName',
    checkers_points: 'checkersName',
    wordle_wins: 'wordleName',
    referral: 'referralsName',
    referrals: 'referralsName',
    ttt: 'tttName',
    checkers: 'checkersName',
});

const LEGACY_ALIASES = Object.freeze({
    ttt: ['tic-tac-toe', 'tic tac toe', 'tictactoe', 'ttt', 'xo', 'крестики', 'нолики', 'крестики-нолики', '井字棋'],
    checkers: ['checkers', 'draughts', 'шашки', '跳棋'],
    bb_best_score: ['block blast', 'blockblast', 'bb', 'блок бласт'],
    saper_wins: ['minesweeper', 'saper', 'сапёр', 'сапер'],
    tower_best: ['tower', 'башня'],
    sudoku_wins: ['sudoku', 'судоку'],
    checkers_wins_pve: ['checkers', 'draughts', 'шашки'],
    wordle_wins: ['wordle', 'вордли'],
    referral: ['referrals', 'referrers', 'рефоводы', 'рефералы'],
});

const ALIAS_KIND = Object.freeze({
    saper_best_6: 'saper_wins', saper_best_8: 'saper_wins',
    saper_best_10: 'saper_wins', saper_best_15: 'saper_wins',
    tower_combo: 'tower_best', checkers_points: 'checkers_wins_pve',
    referrals: 'referral',
});

function botLang(code) {
    const base = String(code || '').trim().toLowerCase().split(/[-_]/, 1)[0];
    if (base === 'in') return 'id'; // legacy Indonesian code
    return Object.hasOwn(COPY, base) ? base : 'en';
}

function botText(lang, key, vars = {}) {
    const copy = COPY[botLang(lang)];
    const template = Object.hasOwn(copy, key) ? copy[key]
        : (Object.hasOwn(COPY.en, key) ? COPY.en[key] : String(key));
    const values = vars && typeof vars === 'object' ? vars : {};
    return template.replace(/\{([A-Za-z][A-Za-z0-9]*)\}/g, (match, name) =>
        Object.hasOwn(values, name) ? String(values[name]) : match);
}

function botGameName(lang, column) {
    const key = Object.hasOwn(GAME_KEYS, column) ? GAME_KEYS[column] : null;
    return key ? botText(lang, key) : String(column || '');
}

function botAliases(lang, kind) {
    const key = Object.hasOwn(GAME_KEYS, kind) ? GAME_KEYS[kind] : null;
    const canonical = key ? [botText(lang, key)] : [];
    const aliasKind = Object.hasOwn(ALIAS_KIND, kind) ? ALIAS_KIND[kind] : kind;
    const legacy = Object.hasOwn(LEGACY_ALIASES, aliasKind) ? LEGACY_ALIASES[aliasKind] : [];
    return [...new Set([...canonical, ...legacy])];
}

module.exports = { botLang, botText, botGameName, botAliases };
